# <center> Exporatory Data Analysis </center>
---

## Objective
---

...

## Strategy
---

...

## Step 0: Import required packages
---

packages:
- [datetime]()
- [io]()
- [cartopy]()
- [matplotlib]()
- [metpy]()
- [siphon]()

In [2]:
# !pip install -q folium cartopy metpy siphon "xarray[complete]"

In [3]:
import folium
import datetime as dt

import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Notice that we will use "plt" to access matplotlib
import matplotlib.pyplot as plt

import metpy.calc as mpcalc
import metpy.plots as mpplots

import numpy as np
import pandas as pd
import geopandas as gpd

from matplotlib.patheffects import withStroke
from metpy.io import parse_metar_file
from metpy.units import pandas_dataframe_to_unit_arrays

# Here is where we import the TDSCatalog class from siphon for obtaining our data 
from siphon.catalog import TDSCatalog

## ...
---

https://thredds.ucar.edu/

In [4]:
# Tornado Data Files
tornado_path_files = '../data/tornadoes/paths_1950-2022.shp'
tornado_starting_point_files = '../data/tornadoes/starting_points_1950-2022.shp'

In [5]:
paths = gpd.read_file(tornado_path_files)
paths

,om,yr,mo,dy,date,time,tz,st,stf,stn,...,loss,closs,slat,slon,elat,elon,len,wid,fc,geometry
0,192,1950,10,1,1950-10-01,21:00:00,3,OK,40,23,...,4.0,0.0,36.7300,-102.5200,36.8800,-102.3000,15.80,10,0,"LINESTRING (-102.52000 36.73000, -102.30000 36..."
1,193,1950,10,9,1950-10-09,02:15:00,3,NC,37,9,...,5.0,0.0,34.1700,-78.6000,34.1701,-78.5999,2.00,880,0,"LINESTRING (-78.60000 34.17000, -78.59990 34.1..."
2,195,1950,11,20,1950-11-20,02:20:00,3,KY,21,1,...,5.0,0.0,37.3700,-87.2000,37.3701,-87.1999,0.10,10,0,"LINESTRING (-87.20000 37.37000, -87.19990 37.3..."
3,196,1950,11,20,1950-11-20,04:00:00,3,KY,21,2,...,5.0,0.0,38.2000,-84.5000,38.2001,-84.4999,0.10,10,0,"LINESTRING (-84.50000 38.20000, -84.49990 38.2..."
4,197,1950,11,20,1950-11-20,07:30:00,3,MS,28,14,...,4.0,0.0,32.4200,-89.1300,32.4201,-89.1299,2.00,37,0,"LINESTRING (-89.13000 32.42000, -89.12990 32.4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68696,621922,2022,9,28,2022-09-28,13:32:00,3,FL,12,0,...,0.0,0.0,28.0830,-80.8669,28.1249,-80.8841,3.00,100,0,"LINESTRING (-80.86690 28.08300, -80.88410 28.1..."
68697,621923,2022,9,30,2022-09-30,10:25:00,3,NC,37,0,...,0.0,0.0,33.9128,-78.2882,33.9132,-78.3011,0.74,20,0,"LINESTRING (-78.28820 33.91280, -78.30110 33.9..."
68698,621924,2022,9,30,2022-09-30,13:22:00,3,NC,37,0,...,0.0,0.0,35.3242,-76.7076,35.3325,-76.7147,0.70,12,0,"LINESTRING (-76.70760 35.32420, -76.71470 35.3..."
68699,621900,2022,9,4,2022-09-04,15:44:00,3,OH,39,0,...,12000.0,0.0,41.0210,-80.6559,41.0220,-80.6555,0.07,15,0,"LINESTRING (-80.65590 41.02100, -80.65550 41.0..."
68700,621901,2022,9,9,2022-09-09,23:21:00,3,SC,45,0,...,0.0,0.0,32.8750,-79.7514,32.8846,-79.7537,0.68,125,0,"LINESTRING (-79.75140 32.87500, -79.75370 32.8..."

In [6]:
# starting_points = gpd.read_file(tornado_starting_point_files)
# starting_points

---

In [8]:
central_lat = 37.5
central_lon = -96
extent = [-120, -70, 24, 50.5]
central_lon = np.mean(extent[:2])
central_lat = np.mean(extent[2:])

plt.figure(figsize=(12, 6))
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent(extent)

ax.add_feature(cfeature.OCEAN)
ax.add_feature(cfeature.LAND, edgecolor='black')
ax.add_feature(cfeature.LAKES, edgecolor='black')
ax.add_feature(cfeature.RIVERS)
ax.gridlines()

: